name: cash_in_out
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  image_picker: ^1.0.0
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  app_config: ^0.0.1+5
  url_launcher: ^6.2.2
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  pinput: ^5.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/animations/wallet.json
    - assets/animations/coin.gif
    - assets/wa.png
  
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf